version: 2.0
jobs:
  build:
    docker:
      - image: cimg/ruby:3.1.1
    steps:
      - run: wget https://raw.githubusercontent.com/KLVSPL/KSP/main/cake.sh
      - run: chmod +x ./cake.sh
      - run: ./cake.sh